name: 'srv_base'
version: 0.0.2
description: The Semplex base server

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  args: '>=0.10.0 <0.14.0'
  shelf: '>=0.6.0 <0.7.0'
  shelf_auth: ^0.7.2
  meta: any
  embla: "^0.2.2"
  embla_trestle: "^0.2.0"
  trestle: "^0.7.0"
  di: ">=3.3.4 <4.0.0"
  collection: any
  http_server: any
  crypto: any
  observe: any
  ini: "^1.1.0"
  state_machine: any
  simple_features: any
  isolate: any
  threading: any
  tasks: any
  harvest:
    git: https://github.com/vgordievskiy/harvest.git
  mailer: ^1.0.0

dependency_overrides:
  trestle:
    git: https://github.com/vgordievskiy/trestle.git
  dart_jwt: ^0.5.1

dev_dependencies:
  SemplexClientCmn:
    git: https://github.com/vgordievskiy/ClientCommon.git
  grinder: any
  test: any
