name: 'tradem_srv'
version: 0.0.2
description: The Semplex base server

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  srv_base:
    git: https://github.com/vgordievskiy/embla_min_version.git
  mustache: any
  googleapis: ">=0.1.0 <0.2.0"
  googleapis_auth: ">=0.1.0 <0.3.0"
  mailer: ^1.0.0
  otp: any

dependency_overrides:
  trestle: ^0.8.0
  dart_jwt: ^0.5.1

dev_dependencies:
  SemplexClientCmn:
    git: https://github.com/vgordievskiy/ClientCommon.git
  grinder: any
  test: any
