name: BMSrv
version: 0.0.1
description: LifeContorol backend.
environment:
  sdk: '>=1.9.1 <2.0.0'
dependencies:
  OntoORM:
    path: externals/OntoORM
  SrvCommon:
    path: externals/SrvCommon
  redstone_web_socket:
    git:
      url: https://github.com/vgordievskiy/redstone_web_socket.git
      ref: eddfd1f755a65d6a1e95ecd2bea0edae52f62c36
  dart_orm: ^0.0.14
  dart_orm_adapter_postgresql: '>=0.0.6 <0.1.0'
  di: '>=3.3.4 <4.0.0'
  event_bus: '>=0.4.0 <0.5.0'
  observe: any
  simple_features: any
  sync_socket: ^1.0.2+1
  threading: ^0.0.7
  ini: "^1.1.0"
  googleapis: ">=0.1.0 <0.2.0"
  googleapis_auth: ">=0.1.0 <0.3.0"
  mailer: any
dependency_overrides:
  dart_orm:
    git: https://github.com/vgordievskiy/DartORM.git
  dart_orm_adapter_postgresql:
    git: https://github.com/vgordievskiy/DartORM-PostgreSQL.git
  redstone:
    git:
      url: https://github.com/vgordievskiy/redstone.git
      ref: new_shelf
dev_dependencies:
  unittest: '>=0.11.5+4 <0.12.0'
