name: BMSrv
version: 0.0.1
description: LifeContorol backend.
environment:
  sdk: '>=1.9.1 <2.0.0'
dependencies:
  OntoORM:
    path: externals/OntoORM
  SrvCommon:
    path: externals/SrvCommon
  dart_orm: ^0.0.14
  dart_orm_adapter_postgresql: '>=0.0.6 <0.1.0'
  di: '>=3.3.4 <4.0.0'
  event_bus: '>=0.4.0 <0.5.0'
  observe: any
  simple_features: any
  sync_socket: ^1.0.2+1
  threading: ^0.0.7
dependency_overrides:
  dart_orm:
    git: https://github.com/vgordievskiy/DartORM.git
dev_dependencies:
  unittest: '>=0.11.5+4 <0.12.0'
